/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ferreandina;

import io.javalin.Javalin;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Javalin.create(
                config -> {
                    config.routes.get("/", ctx -> ctx.result("Javalin testing"));
                }).start(8080);
    }
}
