/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ferreandina;

import com.ferreandina.routes.UserRoute;
import io.javalin.Javalin;

public class App {
    public static void main(String[] args) {
        Javalin.create(
                config -> {
                    new UserRoute(config);
                }).start(8080);
    }
}
