/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("io.javalin:javalin:7.2.2")
    // Javalin Loger
    implementation("org.slf4j:slf4j-simple:2.0.17")
    implementation(platform("org.mongodb:mongodb-driver-bom:5.7.0"))
    implementation("org.mongodb:mongodb-driver-sync")
    // Source: https://mvnrepository.com/artifact/org.json/json
    implementation("org.json:json:20260522")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.21.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.ferreandina.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


tasks.named("run") {
    inputs.files(
        fileTree("src/main/java") {
            include("**/*.java")
        }
    )
}